In [2]:
import torch 
from torch import nn

ModuleNotFoundError: No module named 'torch._utils_internal'

In [6]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")


Using cuda device


In [ ]:
#define dino head
class DinoHead(nn.Module):
    def __init__(self):
        super().__init__()
        self.

In [7]:
input = torch.randn(32, 1, 5, 5)
# With default parameters
print(input.size())
m = nn.Flatten()
output = m(input)
print(output.size())
# With non-default parameters
#m = nn.Flatten(0, 2)
#output = m(input)
#output.size()

torch.Size([32, 1, 5, 5])
torch.Size([32, 25])


In [ ]:
tensor= torch.rand(3,4).to(device)
print(tensor)
print(f"tensor shape: {tensor.shape}")
print(f"dtype:{tensor.dtype}")
print(f"tensor is stored in:{tensor.device}")

tensor([[0.7067, 0.1044, 0.3952, 0.6328],
        [0.9419, 0.1534, 0.4228, 0.5320],
        [0.2838, 0.9751, 0.8238, 0.3816]], device='cuda:0')
tensor shape: torch.Size([3, 4])
dtype:torch.float32
tensor is stored in:cuda:0


In [ ]:
tensor= torch.ones(3,3) 
print(tensor)
tensor.add_(5)
print(tensor)



tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


In [10]:
tensor_2=torch.ones(1).add_(5)
print(tensor_2)
agg=tensor_2.item()
print(agg)

tensor([6.])
6.0
